name: Node CI

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ${{ matrix.os-version }}

    strategy:
      matrix:
        node-version: [12.x]
        os-version: [ubuntu-18.04]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install vsce
        run: npm install -g vsce
      - name: Package extension
        run: |
          tag=${GITHUB_REF#refs/tags/}
          vsce package

